# Generated by Django 3.0.3 on 2021-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_transcation_final_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainadmin',
            name='bottle_numbers',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
