# Generated by Django 3.0.3 on 2021-11-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_mainadmin_bottle_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainadmin',
            name='bottle_numbers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
