# Generated by Django 3.0.3 on 2021-11-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_auto_20211112_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bottle_nos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
