# Generated by Django 3.0.3 on 2021-11-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_customer_bottle_nos'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcation',
            name='bottle_taken',
            field=models.BooleanField(default=False),
        ),
    ]
