# Generated by Django 3.0.3 on 2021-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0017_transcation_bottle_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bottle_nos',
        ),
        migrations.AddField(
            model_name='customer',
            name='bottle_numbers',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
