# Generated by Django 3.0.3 on 2021-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0018_auto_20211112_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='bottle_assigned',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
