# Generated by Django 3.0.3 on 2021-11-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0019_auto_20211114_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='money',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='money_added_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='money updated date'),
        ),
    ]
