# Generated by Django 3.0.3 on 2021-11-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0023_auto_20211115_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcation',
            name='bottle_nums',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
