# Generated by Django 3.0.3 on 2021-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0025_auto_20211121_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
