# Generated by Django 3.0.3 on 2021-11-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0026_auto_20211121_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcation',
            old_name='deliveryPer_uid',
            new_name='delivery_per_name',
        ),
        migrations.RenameField(
            model_name='transcation',
            old_name='delivery_name',
            new_name='delivery_per_uid',
        ),
    ]
