# Generated by Django 3.0.3 on 2021-11-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0027_auto_20211121_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
