# Generated by Django 3.0.3 on 2021-11-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0028_milkvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_temperary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='useraccount.Deliveryperson'),
        ),
    ]
