# Generated by Django 3.0.3 on 2021-11-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0029_auto_20211128_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_temperary',
            new_name='is_temporary',
        ),
    ]
